---
dirs:
    templatedir: $TOPDIR/templates
    etcdir: $TOPDIR/etc
    addonconfdir: $TOPDIR/etc/addon
    tempbase: $TOPDIR/tmp
    outputdir: $TOPDIR/settings
    privatedir: $TOPDIR/private
    playerdir: $TOPDIR/private/player
    machinedir: $TOPDIR/private/machine
    privaddonconfdir: $TOPDIR/private/addon
logging:
    log4perl.logger: INFO, Screen
    log4perl.appender.Screen: Log::Log4perl::Appender::Screen
    log4perl.appender.Screen.layout: Log::Log4perl::Layout::PatternLayout
    log4perl.appender.Screen.stderr: 0
    log4perl.appender.Screen.layout.ConversionPattern: '%d [%-5p] %c %m%n'
levelcap: 90
pretty_print:
    template: $TEMPLATEDIR/pretty_print.lua.template
    lua: /usr/bin/lua
modules:
    - WoWUI::Module::Addons
    - WoWUI::Module::TellMeWhen
    - WoWUI::Module::CombatLogTrigger
    - WoWUI::Module::Quartz
    - WoWUI::Module::LayoutLocal
    - WoWUI::Module::Bagnon
    - WoWUI::Module::Dominos
    - WoWUI::Module::Macros
    - WoWUI::Module::AdiBags
    - WoWUI::Module::kgPanels
    - WoWUI::Module::Mapster
    - WoWUI::Module::OmniCC
    - WoWUI::Module::Broker_uClock
    - WoWUI::Module::Prat
    - WoWUI::Module::KeyBindings
    - WoWUI::Module::NADTTrustList
    - WoWUI::Module::DualBoxMacro
    - WoWUI::Module::NADTQuestShare
    - WoWUI::Module::NADTParty
    - WoWUI::Module::AutoReFollow
    - WoWUI::Module::NADTTurnIn
    - WoWUI::Module::Clique
    - WoWUI::Module::Cork
    - WoWUI::Module::TrinketMenu
    - WoWUI::Module::NPCScan
    - WoWUI::Module::Postal
    - WoWUI::Module::BrokerCurrency
    - WoWUI::Module::Auctionator
    - WoWUI::Module::DeadlyBossMods
    - WoWUI::Module::SexyMap
    - WoWUI::Module::SellJunk
    - WoWUI::Module::FreeRefills
    - WoWUI::Module::ChocolateBar
