---
dirs:
    templatedir: $TOPDIR/templates
    etcdir: $TOPDIR/etc
    addonconfdir: $TOPDIR/etc/addon
    tempbase: $TOPDIR/tmp
    outputdir: $TOPDIR/settings
    privatedir: $TOPDIR/private
    playerdir: $TOPDIR/private/player
    machinedir: $TOPDIR/private/machine
    privaddonconfdir: $TOPDIR/private/addon
logging:
    log4perl.logger: INFO, Screen
    log4perl.appender.Screen: Log::Log4perl::Appender::Screen
    log4perl.appender.Screen.layout: Log::Log4perl::Layout::PatternLayout
    log4perl.appender.Screen.stderr: 0
    log4perl.appender.Screen.layout.ConversionPattern: '%d [%-5p] %c %m%n'
levelcap: 85
modules:
    - WoWUI::Module::Addons
    - WoWUI::Module::KeyBindings
    - WoWUI::Module::WowheadLooter
    - WoWUI::Module::NADTTrustList
    - WoWUI::Module::DualBoxMacro
    - WoWUI::Module::NADTQuestShare
    - WoWUI::Module::NADTParty
    - WoWUI::Module::AutoReFollow
    - WoWUI::Module::NADTTurnIn
    - WoWUI::Module::TellMeWhen
    - WoWUI::Module::tif
    - WoWUI::Module::Clique
    - WoWUI::Module::Cork
    - WoWUI::Module::Raven
    - WoWUI::Module::CombatLogTrigger
    - WoWUI::Module::Digits
    - WoWUI::Module::TrinketMenu
    - WoWUI::Module::TidyPlates
    - WoWUI::Module::NPCScan
    - WoWUI::Module::Bagnon
    - WoWUI::Module::Postal
    - WoWUI::Module::BrokerCurrency
    - WoWUI::Module::Auctionator
    - WoWUI::Module::DeadlyBossMods
    - WoWUI::Module::SexyMap
    - WoWUI::Module::Overachiever
    - WoWUI::Module::WIM
    - WoWUI::Module::SellJunk
    - WoWUI::Module::QuestGuru
    - WoWUI::Module::Hydra
    - WoWUI::Module::FreeRefills
    - WoWUI::Module::Kong
    - WoWUI::Module::ChocolateBar
