
TidyPlatesHubTankCache = {
    ["ColorAttackingOtherTank"] = {
        ["b"] = 0,
        ["g"] = 0.5019607843137255,
        ["r"] = 1,
    },
    ["OpacitySpotlight"] = 0.5,
    ["OpacityTarget"] = 1,
    ["ScaleIgnoreNeutralUnits"] = false,
    ["ClassPartyIcon"] = false,
    ["WidgetsDebuffList"] = {
        ["Lacerate"] = true,
        ["Rake"] = true,
        ["Rip"] = true,
    },
    ["ColorAttackingOthers"] = {
        ["b"] = 0,
        ["g"] = 0.5019607843137255,
        ["r"] = 1,
    },
    ["OpacityFilterNonElite"] = false,
    ["OpacitySpotlightMode"] = 1,
    ["OpacityFullNoTarget"] = true,
    ["ColorDangerGlowMode"] = 1,
    ["WidgetTargetHighlight"] = true,
    ["WidgetsThreatIndicator"] = true,
    ["TextHealthTextMode"] = 1,
    ["WidgetsTotemIcon"] = false,
    ["ColorDangerGlowOnParty"] = false,
    ["ScaleStandard"] = 1,
    ["OpacityNonTarget"] = 0.5,
    ["ColorHealthBarMode"] = 1,
    ["WidgetsRangeIndicator"] = false,
    ["OpacityFilterCustom"] = {
        ["Fanged Pit Viper"] = true,
    },
    ["ColorAggroTransition"] = {
        ["b"] = 1,
        ["g"] = 0.392156862745098,
        ["r"] = 0.1764705882352941,
    },
    ["TextShowLevel"] = false,
    ["ScaleSpotlightMode"] = 1,
    ["OpacityFilterNeutralUnits"] = false,
    ["WidgetEliteIndicator"] = true,
    ["WidgetsThreatIndicatorMode"] = 1,
    ["OpacityFullSpell"] = false,
    ["FrameVerticalPosition"] = 0.2,
    ["ScaleSpotlight"] = 1.2,
    ["WidgetsDebuffMode"] = 1,
    ["WidgetsDebuff"] = true,
    ["ClassColorPartyMembers"] = false,
    ["WidgetsRangeMode"] = 1,
    ["WidgetsComboPoints"] = true,
    ["OpacityFiltered"] = 0,
    ["ColorAttackingMe"] = {
        ["b"] = 1,
        ["g"] = 0.5215686274509804,
        ["r"] = 0.05882352941176471,
    },
    ["ScaleIgnoreNonEliteUnits"] = false,
    ["ClassEnemyIcon"] = false,
}
TidyPlatesHubDamageCache = {
    ["ColorAttackingOtherTank"] = {
        ["b"] = 0,
        ["g"] = 0.5019607843137255,
        ["r"] = 1,
    },
    ["OpacitySpotlight"] = 0.5,
    ["OpacityTarget"] = 1,
    ["ScaleIgnoreNeutralUnits"] = false,
    ["ClassPartyIcon"] = false,
    ["WidgetsDebuffList"] = {
        ["Lacerate"] = true,
        ["Rake"] = true,
        ["Rip"] = true,
    },
    ["ColorAttackingOthers"] = {
        ["b"] = 0,
        ["g"] = 0.5019607843137255,
        ["r"] = 1,
    },
    ["OpacityFilterNonElite"] = false,
    ["OpacitySpotlightMode"] = 1,
    ["OpacityFullNoTarget"] = true,
    ["ColorDangerGlowMode"] = 1,
    ["WidgetTargetHighlight"] = true,
    ["WidgetsThreatIndicator"] = true,
    ["TextHealthTextMode"] = 1,
    ["WidgetsTotemIcon"] = false,
    ["ColorDangerGlowOnParty"] = false,
    ["ScaleStandard"] = 1,
    ["OpacityNonTarget"] = 0.5,
    ["ColorHealthBarMode"] = 1,
    ["WidgetsRangeIndicator"] = false,
    ["OpacityFilterCustom"] = {
        ["Fanged Pit Viper"] = true,
    },
    ["ColorAggroTransition"] = {
        ["b"] = 1,
        ["g"] = 0.392156862745098,
        ["r"] = 0.1764705882352941,
    },
    ["TextShowLevel"] = false,
    ["ScaleSpotlightMode"] = 1,
    ["OpacityFilterNeutralUnits"] = false,
    ["WidgetEliteIndicator"] = true,
    ["WidgetsThreatIndicatorMode"] = 1,
    ["OpacityFullSpell"] = false,
    ["FrameVerticalPosition"] = 0.2,
    ["ScaleSpotlight"] = 1.2,
    ["WidgetsDebuffMode"] = 1,
    ["WidgetsDebuff"] = true,
    ["ClassColorPartyMembers"] = false,
    ["WidgetsRangeMode"] = 1,
    ["WidgetsComboPoints"] = true,
    ["OpacityFiltered"] = 0,
    ["ColorAttackingMe"] = {
        ["b"] = 1,
        ["g"] = 0.5215686274509804,
        ["r"] = 0.05882352941176471,
    },
    ["ScaleIgnoreNonEliteUnits"] = false,
    ["ClassEnemyIcon"] = false,
}
