---
modoptions:
    debug: 0
    enabled: 1
templates:
    perchar:
        combatlogtrigger:
            input: $TEMPLATEDIR/combatlogtrigger/CombatLogTrigger.lua.template
            output: $TEMPDIR/WTF/Account/$ACCOUNT/$REALM/$CHAR/SavedVariables/CombatLogTrigger.lua
perchar_filter:
    addons:
        - CombatLogTrigger
triggers:
    Ritual of Refreshment:
        type: create
        spellid: 92827
        message: '*src is casting *slink, please assist'
        combateither: 1
        filter:
            level: 70
            include:
                - class:Mage
    Ritual of Souls:
        type: create
        spellid: 29893
        message: '*src is casting *slink, please assist'
        combateither: 1
        filter:
            level: 68
            include:
                - class:Warlock
    Divine Guardian:
        type: spell
        message: '*slink up'
        grouptype: [ raid ]
        spellid: 70940
        filter:
            level: 30
            include:
                - all(class:Paladin;spec:Protection;subspec:Divine Guardian)
    Last Stand:
        type: spell
        message: '*slink used'
        reportspellid: 1
        filter:
            level: 20
            include:
                - all(class:Warrior;spec:Protection)
    Rallying Cry:
        type: spell
        message: '*slink used'
        reportspellid: 1
        filter:
            level: 83
            include:
                - class:Warrior
    Guardian of Ancient Kings:
        type: spell
        message: '*slink up'
        reportspellid: 1
        filter:
            level: 85
            include:
                - all(class:Paladin;spec:Protection)
    Icebound Fortitude:
        type: buff
        spellid: 48792
        filter:
            level: 62
            include:
                - all(class:Death Knight;spec:Blood)
    Vampiric Blood:
        type: buff
        spellid: 55233
        filter:
            level: 49
            include:
                - all(class:Death Knight;spec:Blood)
    Shield Wall:
        type: buff
        spellid: 871
        filter:
            level: 48
            include:
                - all(class:Warrior;spec:Protection)
    Survival Instincts:
        type: spell
        message: '*slink up'
        reportspellid: 1
        filter:
            level: 49
            include:
                - all(class:Druid;spec:Feral Combat;subspec:Bear)
    Frenzied Regeneration:
        type: spell
        message: '*slink used'
        reportspellid: 1
        filter:
            level: 52
            include:
                - all(class:Druid;spec:Feral Combat;subspec:Bear)
    Interrupt:
        type: interrupt
        anyspell: 1
        filter:
            - level: 57
              include:
                  - class:Death Knight
            - level: 22
              include:
                  - all(class:Druid;spec:Feral Combat)
            - level: 38
              include:
                  - class:Warrior
            - level: 14
              include:
                  - class:Rogue
            - level: 16
              include:
                  - class:Shaman
            - level: 9
              include:
                  - class:Mage
            - level: 52
              include:
                  - all(class:Warlock;spec:Affliction)
            - include:
                  - race:Blood Elf
    Rebuke:
        type: interrupt
        spellid: 92631
        filter:
            level: 54
            include:
                - class:Paladin
    Hand of Protection:
        type: spell
        spellId: 1022
        filter:
            level: 18
            include:
                - class:Paladin
    Hand of Sacrifice:
        type: spell
        reportspellid: 1
        filter:
            level: 80
            include:
                - class:Paladin
    Hand of Salvation:
        type: spell
        spellId: 1038
        filter:
            level: 66
            include:
                - class:Paladin
    Lay on Hands:
        type: spell
        spellId: 633
        combateither: 1
        filter:
            level: 16
            include:
                - class:Paladin
    Mana Tide Totem:
        type: totem
        grouptype: [ raid ]
        message_summon: "dropped *slink - healers stay in range for extra regen"
        message_destroy: "Mana Tide Totem finished"
        filter:
            level: 49
            include:
                - all(class:Shaman;spec:Restoration)
    Spirit Link Totem:
        type: totem
        message_summon: "dropped *slink - health redistributed for six seconds"
        message_destroy: "Spirit Link finished"
        filter:
            level: 49
            include:
                - all(class:Shaman;spec:Restoration)
    Pain Suppression:
        type: buff
        spellid: 33206
        message_up: "*slink on *tgt up"
        message_down: "*slink on *tgt down"
        filter:
            level: 49
            include:
                - all(class:Priest;spec:Discipline)
    Guardian Spirit:
        type: buff
        reportspellid: 1
        message_up: "*slink on *tgt up"
        message_down: "*slink on *tgt down"
        filter:
            level: 69
            include:
                - all(class:Priest;spec:Holy)
    Purge:
        type: dispel
        reportspellid: 1
        message: "Purge *eslink (*tgt*rtls)"
        filter:
            level: 12
            include:
                - class:Shaman
    Dispel Magic:
        type: dispel
        spellid: 97691
        affiliation: enemy
        filter:
            level: 26
            include:
                - class:Priest
    Spellsteal:
        type: steal
        spellid: 30449
        filter:
            level: 70
            include:
                - class:Mage
    Mass Dispel:
        type: dispel
        reportspellid: 1
        affiliation: enemy
        filter:
            level: 72
            include:
                - class:Priest
    Tranquilizing Shot:
        type: dispel
        message: "Tranq Shot: *eslink (*tgt*rtls)"
        spellid: 19801
        filter:
            level: 76
            include:
                - class:Hunter
    Soothe:
        type: dispel
        reportspellid: 1
        message: "Soothe: *eslink (*tgt*rtls)"
        affiliation: enemy
        filter:
            level: 28
            include:
                - class:Druid
            exclude:
                - spec:Feral Combat
    Rebirth:
        type: spell
        reportspellid: 1
        filter:
            level: 20
            include:
                - class:Druid
    Raise Ally:
        type: spell
        reportspellid: 1
        filter:
            level: 72
            include:
                - class:Death Knight
    Polymorph:
        type: debuff
        reportrefresh: 1
        matchapprox: 1
        filter:
            level: 14
            include:
                - class:Mage
    Bind Elemental:
        type: debuff
        reportrefresh: 1
        spellid: 76780
        filter:
            level: 64
            include:
                - class:Shaman
    Sap:
        type: debuff
        reportspellid: 1
        filter:
            level: 10
            include:
                - class:Rogue
    Shackle Undead:
        type: debuff
        reportrefresh: 1
        reportspellid: 1
        filter:
            level: 32
            include:
                - class:Priest
    Entangling Roots:
        type: debuff
        reportrefresh: 1
        reportspellid: 1
        filter:
            level: 7
            include:
                - class:Druid
    Hibernate:
        type: debuff
        reportrefresh: 1
        reportspellid: 1
        filter:
            level: 48
            include:
                - class:Druid
    Wyvern Sting:
        type: debuff
        spellid: 19386
        filter:
            level: 49
            include:
                - all(class:Hunter;spec:Survival)
    Repentance:
        type: debuff
        reportspellid: 1
        reportrefresh: 1
        filter:
            level: 49
            include:
                - all(class:Paladin;spec:Retribution)
    Blind:
        type: debuff
        reportspellid: 1
        reportrefresh: 1
        filter:
            level: 34
            include:
                - class:Rogue
    Hex:
        type: debuff
        reportspellid: 1
        reportrefresh: 1
        filter:
            level: 80
            include:
                - class:Shaman
    Banish:
        type: debuff
        spellid: 710
        filter:
            level: 32
            include:
                - class:Warlock
    Focus Magic:
        type: buff
        spellid: 54646
        notonself: 1
        message_up: '*slink on *tgt'
        uponly: 1
        combateither: 1
        filter:
            level: 59
            include:
                - all(class:Mage;spec:Arcane)
    Dark Intent:
        type: spell
        reportspellid: 1
        message: '*slink on *tgt'
        filter:
            level: 83
            include:
                - class:Warlock
        combateither: 1
    Fear:
        type: debuff
        reportspellid: 1
        reportrefresh: 1
        filter:
            level: 25
            include:
                - class:Warlock
    Soulstone Resurrection:
        type: buff
        spellid: 20707
        notonself: 
        filter:
            level: 18
            include:
                - class:Warlock
        message_up: '*slink on *tgt'
        uponly: 1
        combateither: 1
